#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=24
#SBATCH --mem=350G
#SBATCH --time=5:00:00
#SBATCH --partition=hera
#SBATCH --exclude=h25c22
#SBATCH --output=/scratch1/RDARCH/rda-ghpcs/Rey.Koki/logs/create_data.%j.log
#SBATCH --account=rda-ghpcs

source /scratch1/RDARCH/rda-ghpcs/Rey.Koki/miniconda3/etc/profile.d/conda.sh
conda activate smoke

python main.py $START_DN $END_DN $YEAR
##python main.py 1 1 2021 
exit 0

