#!/bin/bash

#SBATCH --job-name=thresh
#SBATCH --nodes=1
#SBATCH --ntasks=2                    # total DDP processes = 2 GPUs
#SBATCH --cpus-per-task=20           # number of CPU threads per DDP process
#SBATCH --mem=250G
#SBATCH --time=8:00:00
#SBATCH --qos=gpu
#SBATCH --partition=u1-h100
#SBATCH --gpus=2
#SBATCH --account=gpu-ghpcs

module purge
module load cuda

source /scratch3/BMC/gpu-ghpcs/Rey.Koki/miniconda/etc/profile.d/conda.sh
conda activate cloud

python main.py $CONFIG_FN

exit 0
